---

- name: Install httpd and php modules on CentOS VM
  yum: name={{ item }} state=present update_cache=yes
  with_items:
  - httpd
  - php
  - php-mysql


- name: start the httpd service
  service: name=httpd state=started enabled=yes

#----- create directory for site

# - name: Create ogorodnic1.com directory
#   file: path=/etc/httpd/conf.d/{{ ogo1 }} state=directory owner=apache  group=apache mode=0755

# - name: Create ogorodnic2.com directory
#   file: path=/etc/httpd/conf.d/{{ ogo2 }} state=directory owner=apache  group=apache mode=0755

- name: Ensure that file are included to httpd.conf
  lineinfile: dest=/etc/httpd/conf/httpd.conf  state=present  line='Include conf.d/*.conf'

#  notify:
#    - restart httpd

#------- copy virtual-host config file to vm-box --------#

- name: Create a VirtualHost file for ogorodnic1 VirtualHost
  copy: src=centos_vhost1.conf  dest=/etc/httpd/conf.d/{{ ogo1 }}.conf  owner=apache  group=apache  mode=0755

- name: Create a VirtualHost file for ogorodnic2 VirtualHost
  copy: src=centos_vhost2.conf  dest=/etc/httpd/conf.d/{{ ogo2 }}.conf  owner=apache  group=apache  mode=0755
 

#------- create a log directory/file ---------#

- name: Create ogorodnic1.com directory for logs
  file: path=/var/log/httpd/{{ ogo1 }} state=directory owner=apache  group=apache mode=0755

- name: Create ogorodnic2.com directory for logs
  file: path=/var/log/httpd/{{ ogo2 }} state=directory owner=apache  group=apache mode=0755


#  notify:
#    - restart httpd

- name: Create web directories for ogorodnic1 VirtualHost
  file: path=/var/www/html/{{ ogo1 }}  state=directory  owner=apache  group=apache  mode=0755

- name: Create web directories for ogorodnic2 VirtualHost
  file: path=/var/www/html/{{ ogo2 }}  state=directory  owner=apache  group=apache  mode=0755


#  notify:
#  - restart httpd

#  handlers:
#  - name: restart httpd
#    service: name=httpd  state=restarted
