- name: Install Apache
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
      - apache2
      - libapache2-mod-php5

- name: apache2 listen on port 8081
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
  notify:
     - restart apache2

- name: apache2 virtualhost on port 8081
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
  notify:
     - restart apache2

- name: install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664
