---
- hosts: test-servers
  tasks:
   - name: install Hello World PHP script
     copy: src=index.php dest=/var/www/html/index.php mode=0664

- hosts: centos
  become: true
  tasks: 
  # - name: Copy file to VM
    - copy: src=index.php dest=/var/www/html/index.php

