---
- name: Install dependencies
  apt: pkg={{ item }} state=present 
  become: yes
  with_items:
   - openjdk-8-jdk
   - git
   - wget

- name: Updating APT package cache
  become: yes
  action: apt update_cache=yes

- name: Download jenkins repo
  shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
  become: yes

- name: Add Jenkins repository
  shell: sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ | tee -a /etc/apt/sources.list' 
  become: yes  

- name: Install Jenkins
  apt: name=jenkins state=present
  become: true
